### ISSUE TITLE
Get Started CLI version update

### ISSUE THREAD

**Issue by ele7ija** [absmach/supermq-docs#104]
**BUG REPORT**

1. What were you trying to achieve?

Go through the [ _Get Started_](https://github.com/mainflux/docs/blob/master/docs/getting-started.md).

2. What are the expected results?

Reproducing the same results presented in the Get Started.

3. What are the received results?

`mainflux-users         | {"level":"warn","message":"Method register for user jolly_bhabha@email.com took 2.043883ms to complete with error: password does not meet the requirements.","ts":"2021-11-22T16:59:49.275523438Z"}
`

4. What are the steps to reproduce the issue?

Go through the exact steps from the Get Started.

5. In what environment did you encounter the issue?

GOARCH=amd64

6. Additional information you deem important:

The problem is caused by the fact that CLI v0.9.0 uses the password "123" for that test which doesn't match the new default regex `^.{8,}`. 

It does say in the Get Started: `here we use release 0.9.0 but be sure to use the latest release`, however I would argue that the Get Started should work off the bat (just link the new version) or at least there should be a link to [https://github.com/mainflux/mainflux/releases](https://github.com/mainflux/mainflux/releases).

**Comment by drasko** [comment]
It would be good to see PR fixing this.
