### ISSUE TITLE
Online version of documentation doesn't match with latest commit

### ISSUE THREAD

**Issue by jonathandreyer** [absmach/supermq-docs#11]
**BUG REPORT**

1. What were you trying to achieve?
The latest version of [Mainflux Read The Docs page](https://mainflux.readthedocs.io/en/latest/) does not match with latests commits.

2. What are the expected results?

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

**Comment by nmarcetic** [comment]
@jonathandreyer This is normal and latest commit (e.g master branch or latest docker images) are work in progress and there can be breaking changes, bugs, etc... You should always use latest version, which is [0.10.0](https://github.com/mainflux/mainflux/releases) and docker images with `0.10.0` tag. You can use the latest or master branch if you want to try/test new features etc...
What exactly did you find as not matching?

**Comment by jonathandreyer** [comment]
@nmarcetic Thanks for your response. I understand but maybe it is more logical to have the version (*latest*) based on the up-to-date master branch and the *stable* version of the latest stable version. What do you think?
Actually, the *latest* version of *Read the Docs* doesn't reflect the latest commits.

**Comment by nmarcetic** [comment]
@jonathandreyer I agree but it's really hard to keep it up to date :) We need help

**Comment by chombium** [comment]
As I haven't been active for a while, I was thinking to read the docs and the code to catch up. I will check the docs and update it.

@nmarcetic It would be nice if we have different versions of the docs for different released versions of Mainflux. Readthedocs has some [features](https://docs.readthedocs.io/en/stable/versions.html) to version the docs. I will take a look at them too.

**edit:** I've just seen that we already have `latest` and `stable` version of the docs,vso we actually need to update them.

**Comment by nmarcetic** [comment]
I agree that it would be awesome @chombium I saw this many times, it's really useful.

**Comment by dramasamy** [comment]
@jonathandreyer Please execute the following commands inside the 'docs' repo and browse the latest document. 

```
pip install mkdocs  (or)  pip3 install mkdocs
mkdocs serve
```

Please log multiple bugs with what's missing in the latest docs so that we can start fixing them.

**Comment by rodneyosodo** [comment]
@jonathandreyer docs are being published to [docs.mainflux.io](https://docs.mainflux.io/)
