### ISSUE TITLE
Correct Thing creation docs

### ISSUE THREAD

**Issue by drasko** [absmach/supermq-docs#117]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Add both creation approaches (single and bulk) to Things API reference.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by manuio** [comment]
Resolved here: https://github.com/mainflux/docs/pull/120
