### ISSUE TITLE
Addons: trying to save messages into influxdb

### ISSUE THREAD

**Issue by marijadstankovic** [absmach/supermq-docs#42]
I'm trying to save sent messages using addons (Influxdb) while using mqtt. My application works fine - the messages are sent and received, but when I try to read them, none are saved. I saw in [one old example](https://medium.com/mainflux-iot-platform/mainflux-open-source-iot-platform-set-up-and-usage-70bed698791a)  using http that I should add content type header, but mqtt doesn't have that option. I saw here something like having special topic "/ct" but I don't understand how to use this.

The mainflux I'm using is from April 29. this year. Writer and reader are installed successfully.

My apps are in python, so I'm using paho library.

Here is my code:

app sending data

![image](https://user-images.githubusercontent.com/58818571/85763595-1acc1500-b715-11ea-8a02-11096c1ae17b.png)
![image](https://user-images.githubusercontent.com/58818571/85763742-3fc08800-b715-11ea-8240-0e121a491ba4.png)

app showing data (partially):

![image](https://user-images.githubusercontent.com/58818571/85764028-84e4ba00-b715-11ea-97c5-501f8f61b209.png)
![image](https://user-images.githubusercontent.com/58818571/85764078-91691280-b715-11ea-9f5c-af27c0b83c83.png)

app trying to read the messages from influxdb:

![image](https://user-images.githubusercontent.com/58818571/85764424-c07f8400-b715-11ea-91de-1cd6019dd7bb.png)

**Comment by blokovi** [comment]
Find in log for influxdb-writter if messages is saved at all when you send them. Keep in mind that message must be in SenML format to be saved in database, try with message from [documentation ](https://mainflux.readthedocs.io/en/latest/messaging/#mqtt).
Content-type subtopic is not used anymore, that is old blog post.

**Comment by marijadstankovic** [comment]
The messages I was originally sending are:

![image](https://user-images.githubusercontent.com/58818571/85779411-db58f500-b723-11ea-957a-1922321bfaf4.png)

When I try to send a message from [example ](https://mainflux.readthedocs.io/en/latest/getting-started/#step-4-send-messages) I don't see anything in writer neither:
![image](https://user-images.githubusercontent.com/58818571/85780468-f11aea00-b724-11ea-99ce-5b22b1aebf51.png)


![image](https://user-images.githubusercontent.com/58818571/85780342-cd57a400-b724-11ea-8f25-54d37dca7994.png)
![image](https://user-images.githubusercontent.com/58818571/85780373-d6e10c00-b724-11ea-8c72-8f137495c90d.png)

**Comment by mteodor** [comment]
can you pull latest images? there was some bug that caused messages not being propagated via nats to writers

**Comment by marijadstankovic** [comment]
Perfect!
Pulled the last images (docker-compose -f docker/docker-compose.yml pull) and updated the project (git pull) and now it works
Thanks! 😄

**Comment by manuio** [comment]
@marijadstankovic great! Closing this one.
