### ISSUE TITLE
Kubernetes installation steps need an update

### ISSUE THREAD

**Issue by dramasamy** [absmach/supermq-docs#70]
**BUG REPORT**

1. What were you trying to achieve?
Install MF in Kubernetes cluster

2. What are the expected results?
Successful installation of MF on Kubernetes by following the MF documentation

3. What are the received results?
Couldn't install MF on Kubernetes via Helm

dramasam@Dineshs-MacBook-Pro mainflux % helm repo add stable https://kubernetes-charts.storage.googleapis.com/
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead
dramasam@Dineshs-MacBook-Pro mainflux % helm repo add stable https://charts.helm.sh/stable                    
"stable" has been added to your repositories
dramasam@Dineshs-MacBook-Pro mainflux % helm dependency update                                                
Error: no repository definition for @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami. Please add them via 'helm repo add'

4. What are the steps to reproduce the issue?
Follow the steps in https://mainflux.readthedocs.io/en/latest/kubernetes/

5. In what environment did you encounter the issue?
😄  minikube v1.14.2 on Darwin 10.15.6
✨  Using the vmware driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🎉  minikube 1.17.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.17.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'
🔄  Restarting existing vmware VM for "minikube" ...
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.12 ...
🔗  Configuring Calico (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" by default

6. Additional information you deem important:
dramasam@Dineshs-MacBook-Pro mainflux % helm repo add stable https://kubernetes-charts.storage.googleapis.com/
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead
dramasam@Dineshs-MacBook-Pro mainflux % helm repo add stable https://charts.helm.sh/stable                    
"stable" has been added to your repositories
dramasam@Dineshs-MacBook-Pro mainflux % helm dependency update                                                
Error: no repository definition for @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami, @bitnami. Please add them via 'helm repo add'

**Comment by drasko** [comment]
Nice bug report ;)
